### ISSUE TITLE
Share your opinion on this repo

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-The-Library#2]
@ivsimaku  could you go over this repo and let me know what do you think. I'm interested in:

Dose the folder structure make sense
Are the section in each README in the right order
Is there something worth adding
Maybe removing
What I'm not interested in

spell check and grammar, since I'll send the text for proofing.

**Comment by ivsimaku** [comment]
@davidgatti Great work on this

My only suggestion is that the majority of the folders have just the Readme, I would probably add another file in there so we can show how others can contribute to that folder and the information that pertains to it.

Also, another suggestions that I have been meaning to discuss with you has been regarding Comments in code. I do not think it's a good idea to have comments numbered. The issue with that is if I add a new line of code on top, I have to re-number everything. This is just something to think about.

Let me know if I missed anything.
